#!/bin/sh
set -e

case $1 in
    install|upgrade)
        conflicts="
        /usr/share/applications/mimeapps.list
        /usr/lib/modprobe.d/panfrost.conf
        /usr/share/wayland-sessions/plasmawayland.desktop
        /usr/share/gdm/gdm.schemas
        "
        for i in $conflicts
        do
            dpkg-divert --package radxa-system-config-rockchip --divert "$i.bak" --rename "$i"
        done
        ;;
esac
    
#DEBHELPER#

exit 0