#!/bin/sh
set -e

case $1 in
    configure)
        if [ ! -e /etc/security ]
        then
            mkdir -p /etc/security
        fi
        if [ -e /etc/security/pam_env.conf ] && ! grep -e 'QT_QUICK_BACKEND' /etc/security/pam_env.conf >/dev/null 2>/dev/null
        then
            echo 'QT_QUICK_BACKEND DEFAULT=software' >> /etc/security/pam_env.conf
        fi

        dpkg-trigger update-initramfs
        ;;
esac
    
#DEBHELPER#

exit 0
