monitor.alsa.rules = [
  {
    matches = [
      {
        media.class = "Audio/Source"
        api.alsa.card.name = "~^sunxi-ac101b?$"
        api.alsa.pcm.stream = "capture"
      }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
      }
    }
  }
]
